CXX        := c++
CXXFLAGS   := -Wall -Wextra -Werror -std=c++17
SRCS       := main.cpp Fixed.cpp
OBJS       := $(SRCS:.cpp=.o)
NAME       := a.out

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp Fixed.hpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
