NAME    = brain

CXX     = c++
CXXFLAGS= -Wall -Wextra -Werror -std=c++17 -fsanitize=address

SRCS    = Animal.cpp \
          Dog.cpp    \
          Cat.cpp    \
          Brain.cpp  \
          main.cpp

OBJS    = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
